apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: myapp-argo-application
  namespace: argocd
spec: 
  project: default

  source: 
    repoURL: https://github.com:benjaminade/cap-argocd.git
    targetRevision: HEAD
    path: test-app-deploy
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true