apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: kube-system
data:
  elasticsearch.yml: |
    cluster.name: benade-eks-0VdYNoTK
    node_name: ip-10-0-1-118.ec2.internal 
    network.host: sitekubectl 
    http.port: 9200
  elasticsearch-env: |
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"